import os

STARTING_CAPITAL = 200000

MAX_RISK_PER_TRADE = 0.01
MAX_DAILY_LOSS = 0.02
MAX_POSITION_PERCENT = 0.20

STOP_LOSS_PERCENT = 0.005
TAKE_PROFIT_PERCENT = 0.010

SYMBOL = "RELIANCE"

SYMBOLS = [
    "AUBANK",
    "AXISBANK",
    "BANDHANBNK",
    "BANKBARODA",
    "FEDERALBNK",
    "HDFCBANK",
    "ICICIBANK",
    "IDFCFIRSTB",
    "INDUSINDBK",
    "KOTAKBANK",
    "PNB",
    "SBIN",
]
POLL_SECONDS = 60

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

MAX_OPEN_POSITIONS = 1
