import os

STARTING_CAPITAL = 10000

MAX_RISK_PER_TRADE = 0.01
MAX_DAILY_LOSS = 0.02
MAX_POSITION_PERCENT = 0.20

STOP_LOSS_PERCENT = 0.005
TAKE_PROFIT_PERCENT = 0.010

SYMBOL = "RELIANCE"
POLL_SECONDS = 60

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
